"""
Send a formatted morning brief to Telegram.
Reads all data files generated by the pipeline and sends
multi-part messages via the Telegram Bot API.
"""
import os, sys, json, urllib.request, urllib.error, urllib.parse
from datetime import datetime, timezone, timedelta

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from build_dashboard import generate_bottom_line  # shared logic with the dashboard

DATA_DIR = os.path.join(SCRIPT_DIR, "..", "data")
INSTRUMENTS = ["Gold", "NAS100", "EURUSD"]
MAX_LEN = 4000  # leave headroom under 4096 Telegram limit

# ── helpers ──────────────────────────────────────────────────────────

def fmt(v, decimals=2):
    if v is None: return "\u2014"
    if isinstance(v, float):
        if abs(v) < 10: return f"{v:.4f}"
        return f"{v:,.{decimals}f}"
    if isinstance(v, int): return f"{v:,}"
    return str(v)

def pct(v): return f"{v:.1f}%" if v is not None else "\u2014"

def emoji(val):
    if val is None: return "\u2796"
    if val > 0: return "\u25b2"
    if val < 0: return "\u25bc"
    return "\u27a1"

def load(path):
    p = os.path.join(DATA_DIR, path)
    if os.path.exists(p):
        with open(p) as f: return json.load(f)
    return {}

def esc(s):
    """Escape HTML reserved chars for Telegram."""
    return str(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")

# ── build messages ───────────────────────────────────────────────────

def build_all(scores, ome, vol_range, events_data, cot_data, geo):
    msgs = []
    _add_general(msgs, scores, events_data, vol_range)
    for instr in INSTRUMENTS:
        _add_instrument(msgs, instr, scores, ome, vol_range, cot_data, geo)
    _add_events(msgs, events_data)
    _add_geopolitical(msgs, geo)
    return msgs

def _start_msg(text):
    return f"<b>\U0001f4ca Morning Brief</b> \u2014 {text}"

def _add_general(msgs, scores, events_data, vol_range):
    overall = scores.get("overall", {})
    sig = overall.get("signal", "NEUTRAL")
    score = overall.get("avg_score", 0)
    macro = scores.get("macro", {}).get("score", 0)
    gen = scores.get("generated", "")
    gen_t = ""
    if gen:
        try:
            dt = datetime.fromisoformat(gen)
            gen_t = dt.strftime("%a %d %b %H:%M")
        except: pass

    lines = [_start_msg(gen_t or "Market Dashboard")]
    lines.append("")
    lines.append(f"Overall: <b>{sig}</b> ({score:+.1f})  |  Macro: {macro:+.1f}")
    lines.append("")

    # Vol / Range summary
    vr = vol_range.get("instruments", {})
    for instr in INSTRUMENTS:
        v = vr.get(instr, {})
        s = scores.get("instruments", {}).get(instr, {})
        sig_i = s.get("signal", "?")
        ts = s.get("total_score", 0)
        lines.append(
            f"{instr}: <b>{sig_i}</b> ({ts:+d})  "
            f"HL {pct(v.get('high_low_range_median'))} "
            f"OC {pct(v.get('open_close_median'))} "
            f"Vol {pct(v.get('volatility_annualized'))}"
        )
    msgs.append("\n".join(lines))

def _add_instrument(msgs, instr, scores, ome, vol_range, cot_data, geo):
    s = scores.get("instruments", {}).get(instr, {})
    oi = ome.get(instr, {})

    sig = s.get("signal", "?")
    ts = s.get("total_score", 0)
    sp = oi.get("underlying_price")

    bottom_line = generate_bottom_line(instr, s, oi)

    lines = [
        f"\n<b>{emoji(ts)} {instr} \u2014 {sig} ({ts:+d})</b> | Price: {fmt(sp)}",
        esc(bottom_line),
    ]
    msgs.append("\n".join(lines))

def _add_events(msgs, events_data):
    events = events_data.get("events", [])
    if not events:
        return

    # Filter to today / upcoming high-impact
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    upcoming = [e for e in events if e.get("impact") in ("High", "Medium")]
    # Limit to next 8
    upcoming = upcoming[:8]

    if not upcoming:
        return

    lines = [f"\n\U0001f4c5 <b>Key Events</b>"]
    for e in upcoming:
        title = esc(e.get("title", ""))
        country = e.get("country", "")
        impact = e.get("impact", "")
        dt_raw = e.get("date", "")
        time_str = ""
        if dt_raw:
            try:
                dt = datetime.fromisoformat(dt_raw)
                time_str = dt.strftime("%H:%M")
            except: pass
        imp_icon = "\u26a0" if impact == "High" else "\U0001f4c4"
        fc = e.get("forecast", "")
        prev = e.get("previous", "")
        extra = ""
        if fc and prev:
            extra = f" (f/c {fc}, prev {prev})"
        elif fc:
            extra = f" (f/c {fc})"
        lines.append(f"  {imp_icon} {time_str} {title}{extra}")
    msgs.append("\n".join(lines))

def _add_geopolitical(msgs, geo):
    articles = geo.get("articles", [])
    if not articles:
        return
    top = articles[:4]
    lines = [f"\n\U0001f30d <b>Geopolitical</b>"]
    for a in top:
        title = esc(a.get("title", ""))
        dom = a.get("domain", "")
        rel = a.get("relevance", 0)
        lines.append(f"  \u2022 [{dom}] {title} (rel {rel})")
    msgs.append("\n".join(lines))

# ── send ─────────────────────────────────────────────────────────────

def send_msg(token, chat_id, text):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "HTML",
        "disable_web_page_preview": "true",
    }).encode()
    req = urllib.request.Request(url, data=data, method="POST")
    try:
        resp = urllib.request.urlopen(req)
        return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"Telegram API error {e.code}: {body}")
        return None

def run():
    token = os.environ.get("TG_TOKEN") or os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TG_CHAT") or os.environ.get("TELEGRAM_CHAT_ID")
    page_url = os.environ.get("PAGE_URL", "")

    if not token or not chat_id:
        print("Telegram secrets not set — skipping")
        return True

    scores = load("scores.json")
    ome = load("ome_data.json").get("instruments", {})
    vol_range = load("vol_range.json")
    events_data = load("events.json")
    cot_data = load("cot_data.json").get("instruments", {})
    geo = load("geopolitical.json")

    if not scores.get("instruments"):
        print("No scores data — cannot build brief")
        return True

    msgs = build_all(scores, ome, vol_range, events_data, cot_data, geo)

    # Footer with link appended to last message
    if page_url:
        msgs[-1] += f"\n\n<a href='{esc(page_url)}'>Open Dashboard</a>"

    sent = 0
    for text in msgs:
        text = text.strip()
        if not text:
            continue
        # Split if too long
        while len(text) > MAX_LEN:
            split_at = text.rfind("\n", 0, MAX_LEN)
            if split_at < 1: split_at = MAX_LEN
            part = text[:split_at]
            text = text[split_at:].strip()
            result = send_msg(token, chat_id, part)
            if result and result.get("ok"):
                sent += 1
        result = send_msg(token, chat_id, text)
        if result and result.get("ok"):
            sent += 1

    print(f"Sent {sent} Telegram message(s)")
    return True

if __name__ == "__main__":
    run()
